import json

summaries = [
"""Supervised contrastive learning (SupCon) is widely used to shape representations, but has seen limited targeted study for audio deepfake detection. Existing work typically combines contrastive terms with broader pipelines; however, the focus on SupCon itself is missing. In this work, we run a controlled study on wav2vec2 XLS-R (300M) that varies (i) similarity in SupCon (cosine vs angular similarity derived from the hyperspherical angle) and (ii) negative scaling using a warm-started global cross-batch queue. Stage 1 fine-tunes the encoder and projection head with SupCon; Stage 2 freezes them and trains a linear classifier with BCE. Trained on ASVspoof 2019 LA and evaluated on ASV19 eval plus ITW and ASVspoof 2021 DF/LA, Cosine SupCon with a delayed queue achieves the best ITW EER (8.29%) and pooled EER (4.44), while angular similarity performs strongly without queued negatives (ITW 8.70), indicating reduced reliance on large negative sets.""",

"""Preserving a speaker's voice identity while generating speech in a different language remains a fundamental challenge in spoken language technology, particularly in specialized domains such as scientific communication. In this paper, we address this challenge through our system submission to the International Conference on Spoken Language Translation (IWSLT 2026), the Cross-Lingual Voice Cloning shared task. First, we evaluate several state-of-the-art voice cloning models for cross-lingual speech generation of scientific texts in Arabic, Chinese, and French. Then, we build voice cloning systems based on the OmniVoice foundation model. We employ data augmentation via multi-model ensemble distillation from the ACL 60/60 corpus. We investigate the effect of using this synthetic data for fine-tuning, demonstrating consistent improvements in intelligibility (WER and CER) across languages while preserving speaker similarity.""",

"""Digital biomarkers for depression have largely relied on static acoustic descriptors, pooled summary statistics, or conventional machine learning representations. Such approaches may miss nonlinear temporal organization embedded in conversational vocal dynamics. We hypothesized that depression is associated with altered recurrence structure in vocal state trajectories, reflecting changes in how the vocal system revisits acoustic states over time. Using the depression subset of the DAIC-WOZ corpus with 142 labeled participants, we modeled frame-level COVAREP trajectories as nonlinear dynamical systems and derived recurrence-based biomarkers from 74 vocal channels. Logistic regression with feature selection and stratified cross-validation evaluated classification performance. Recurrence-based biomarkers achieved a mean cross-validated AUC of 0.689, exceeding static acoustic baselines, entropy-dynamics features, Hurst exponent features, determinism features, and Lyapunov-like instability proxies. Permutation testing indicated statistical significance with $p=0.004$. Pooled cross-validated predictions yielded AUC 0.665 with a 95\% bootstrap confidence interval of [0.568, 0.758]. These findings suggest that depression may be characterized by altered recurrence structure in conversational vocal dynamics and support nonlinear state-space analysis as a promising direction for digital psychiatric biomarkers.""",

"""To preserve or not to preserve prosody is a central question in voice anonymization. Prosody conveys meaning and affect, yet is tightly coupled with speaker identity. Existing methods either discard prosody for privacy or lack a principled mechanism to control the utility-privacy trade-off, operating at fixed design points. We propose DiffAnon, a diffusion-based anonymization method with classifier-free guidance (CFG) that provides explicit, continuous inference-time control over prosody preservation. DiffAnon refines acoustic detail over semantic embeddings of an RVQ codec, enabling smooth interpolation between anonymization strength and prosodic fidelity within a single model. To the best of our knowledge, it is the first voice anonymization framework to provide structured, interpolatable inference-time prosody control. Experiments demonstrate structured trade-off behavior, achieving strong utility while maintaining competitive privacy across controllable operating points.""",

"""Conventional neural speech codecs suffer from severe intelligibility degradation at ultra-low bitrates, where the bottleneck transitions from acoustic distortion to semantic loss. To address this issue, this paper conducts a systematic investigation into the role and fundamental limits of integrating frozen semantic priors -- specifically HuBERT and Whisper -- into neural speech coding. We introduce and quantitatively validate a novel Semantic Retirement phenomenon: while semantic constraints reduce the Word Error Rate (WER) by up to ~10% relatively at 1.5 kbps, their benefits rapidly diminish beyond 6 kbps, indicating a practical capacity boundary. We further uncover a clear trade-off between different prior types: acoustic-rich priors (HuBERT) better preserve prosodic and timbral details, whereas high-level linguistic priors (Whisper) effectively suppress phonetic hallucinations in noisy environments (reducing hallucination rates by 26 percent) and substantially narrow the generalization gap for unseen speakers. Building on these findings, we propose a bitrate-aware regulation strategy that dynamically adjusts prior strength to optimize the trade-off between semantic consistency and perceptual naturalness. Extensive experimental evaluations confirm that our approach achieves competitive intelligibility and noise robustness compared to existing baselines, offering a principled pathway toward ultra-low-bitrate generative speech coding.""",

"""Cross-lingual speaker verification suffers from severe language-speaker entanglement. This causes systematic degradation in the hardest scenario: correctly accepting utterances from the same speaker across different languages while rejecting those from different speakers sharing the same language. Standard adversarial disentanglement degrades speaker discriminability; blind discriminators inadvertently penalize speaker-discriminative traits that merely correlate with language. To address this, we propose Dual-LoRA, injecting trainable task-factorized LoRA adapters into a frozen pre-trained backbone. Our core innovation is a Language-Anchored Adversary: by grounding the discriminator with an explicit language branch, adversarial gradients target true linguistic cues rather than arbitrary correlations, preserving essential speaker characteristics. Evaluated on the TidyVoice benchmark, our system achieves a 0.91% validation EER and achieves 3rd place in the official challenge.""",

"""Objective metrics for emotional expressiveness are vital for speech generation, particularly in expressive synthesis and voice conversion requiring emotional prosody transfer. To quantify this, the field widely relies on emotion similarity between reference and generated samples. This approach computes cosine similarity of embeddings from encoders like emotion2vec, assuming they capture affective cues despite linguistic and speaker variations. We challenge this assumption through controlled adversarial tasks and human alignment tests. Despite high classification accuracy, these latent spaces are unsuitable for zero-shot similarity evaluation. Representational limitations cause linguistic and speaker interference to overshadow emotional features, degrading discriminative ability. Consequently, the metric misaligns with human perception. This acoustic vulnerability reveals it rewards acoustic mimicry over genuine emotional synthesis.""",

"""Audio-based stuttering systems to date have been trained for detection -- what disfluency is present now -- leaving prediction, the capability needed for closed-loop intervention, unstudied at deployable scale. We train a 616K-parameter CNN on SEP-28k (Apple, 20,131 three-second clips) to predict whether the next contiguous clip contains any disfluency. (1) Severity-selective precursor signal: on the episode-grouped test set, aggregate preblock AUC is modest (0.581 [0.542, 0.619]), but stratifying by upcoming event type reveals concentration on clinically severe events -- blocks 0.601 [0.554, 0.651] and sound repetitions 0.617 [0.567, 0.667] both exclude chance, while fillers (0.45) and word repetitions (0.49) are at chance. The aggregate objective converges to a severity-selective predictor because severe events carry prosodic precursors; fillers do not. (2) Cross-population transfer: without fine-tuning, the same checkpoint applied to 1,024 pediatric Children-Who-Stutter utterances (FluencyBank Teaching) attains AUC 0.674 detection and 0.655 prediction; DisfluencySpeech and LibriStutter reach 0.58-0.60 AUC. (3) Deployable on-device: lossless export to CoreML (1.19 MB), ONNX (40 KB), TFLite. Neural-Engine latency per 3 s window: 0.25 ms (iPhone 17 Pro Max, A19 Pro) to 0.55 ms (iPhone SE 3rd-gen and M1 Max). A 4 Hz streaming simulation uses 0.54% of the real-time budget. Platt-calibrated outputs (test ECE 0.010, from 0.177 raw). Five negative ablations -- output-level Future-Guided Learning, multi-clip GRU, time-axis concatenation, asymmetric focal loss, direct block-targeted training -- none improved over the vanilla baseline.""",

"""We propose a knowledge-driven approach to speech target extraction in the presence of background sound effects already recorded in cinematic audio. The specific knowledge sources studied are manners of articulation that are detected in speech frames and adopted to form a knowledge vector as a part of features to enhance speech separation and target speech extraction because some short speech segments are often difficult to separate from mixed background sounds. Testing on the recent Sound Demixing Challenge data for cinematic audio source separation (CASS) shows that utilizing articulator-aware knowledge sources produces better separation results than those obtained without using any knowledge, especially for speech segments buried in unspecified background sound events.""",

"""Multi-talker automatic speech recognition (ASR) in conversational recordings remains an open problem, particularly in scenarios with large portion of overlapping speech where identifying and transcribing a target speaker is difficult from audio alone. Visual cues can help resolve speaker ambiguity, yet their integration into long-context audio-visual (AV) ASR systems has been limited. The CHiME-9 MCoRec task addresses this challenge by requiring transcription of audio-visual recordings of heavily-overlapped parallel conversations, followed by clustering the participants into conversational groups. In this work, we present the BUT system based on a long-context target-speaker AV-ASR model capable of processing long-form recordings in a single decoding pass. Our architecture conditions a pre-trained NVIDIA Parakeet-v2 ASR model on visual representations from a pre-trained AV-HuBERT model. To cluster participants into conversation groups, we employ Qwen3.5-122B LLM to estimate transcript topic similarity followed by hierarchical agglomerative clustering. On the MCoRec development set, the proposed system achieves 33.7% WER and a clustering F1 score of 0.97, improving over the official baseline by 16.2% WER and 0.15 F1 absolute. On the eval set, our team ranked second, being 0.16% WER and 0.5% F1 worse than the best system.""",

"""We introduce LRS-VoxMM, an in-the-wild benchmark for audio-visual speech recognition (AVSR). The benchmark is derived from VoxMM, a dataset of diverse real-world spoken conversations with human-annotated transcriptions. We select AVSR-suitable samples and preprocess them in an LRS-style format for direct use in existing AVSR pipelines. Compared with commonly used benchmarks, LRS-VoxMM covers a more diverse range of scenarios and acoustic conditions. We also release distorted evaluation sets with additive noise, reverberation, and bandwidth limitation to support evaluation under severe acoustic degradation. Experimental results show that LRS-VoxMM is considerably harder than LRS3 and that the contribution of visual information becomes more evident as the audio signal degrades. LRS-VoxMM supports more realistic AVSR benchmarking and encourages further research on the role of visual information in challenging real-world conditions.""",

"""Animals hear and vocalize across frequency ranges that differ substantially from humans, often extending into the ultrasonic domain. Yet most computational bioacoustics systems rely on audio models pre-trained at 16 kHz, restricting their usable bandwidth to the 0-8 kHz baseband and discarding higher-frequency information present in many bioacoustic recordings. We investigate a multi-band encoding framework that decomposes the full spectrum of animal calls into band features and fuses them into a unified representation. Similarity analyses on models show that certain encoders produce decorrelated band embeddings that improve class separation after fusion. Classification experiments on three bioacoustic datasets using eight pre-trained models and five fusion strategies show that fused representations consistently outperform the baseband and time-expansion baselines on two datasets, showing the potential of multi-band methods for full-spectrum encoding of animal calls."""
]

chinese_summaries = [
    "<ul>\n    <li><b>受监督对比学习研究</b>：针对音频深度伪造检测，在 wav2vec2 XLS-R (300M) 模型上对受监督对比学习 (SupCon) 进行了对照研究。</li>\n    <li><b>相似度指标对比</b>：对比了余弦相似度和基于超球面角的角相似度，并测试了负样本缩放策略的影响。</li>\n    <li><b>最佳检测性能</b>：结合延迟队列的余弦 SupCon 在实际场景 (ITW) 和汇集测试中取得了最低的等错误率 (EER)，而角相似度在减少对大规模负样本依赖的情况下也表现出色。</li>\n</ul>",
    "<ul>\n    <li><b>跨语言语音克隆挑战</b>：旨在解决跨语言语音生成中保持说话人身份特征的难题，特别是在科学交流等专业领域。</li>\n    <li><b>模型评估与构建</b>：评估了多种先进的跨语言语音克隆模型，并基于 OmniVoice 基础模型构建了针对阿拉伯语、中文和法语的科学文本语音克隆系统。</li>\n    <li><b>数据增强与性能提升</b>：采用多模型集成蒸馏技术生成合成数据进行微调，有效提升了跨语言语音的清晰度（降低了词错误率和字符错误率），同时保持了良好的说话人相似度。</li>\n</ul>",
    "<ul>\n    <li><b>新型抑郁症生物标志物</b>：提出利用对话语音中的非线性循环动态特征作为抑郁症的数字生物标志物，而非传统的静态声学特征。</li>\n    <li><b>非线性动力学建模</b>：使用 DAIC-WOZ 数据集，将语音状态轨迹建模为非线性动力系统，并从中提取基于循环结构的特征。</li>\n    <li><b>分类性能优势</b>：这些基于循环的生物标志物在分类预测中表现出优于传统声学基线的性能（平均交叉验证 AUC 达 0.689），证明了非线性状态空间分析在精神健康监测中的潜力。</li>\n</ul>",
    "<ul>\n    <li><b>语音匿名化中的韵律控制</b>：提出了一种名为 DiffAnon 的基于扩散模型的语音匿名化方法，旨在解决现有方法在保护隐私和保留韵律（情感与语义）之间的固定权衡问题。</li>\n    <li><b>连续且明确的控制机制</b>：利用无分类器引导 (CFG) 技术，首次在推理阶段实现了对韵律保留程度的连续且明确的控制。</li>\n    <li><b>性能优越</b>：实验证明，该框架能在单一模型内平滑调节匿名化强度和韵律保真度，在保持高度隐私保护的同时，实现良好的语音效用。</li>\n</ul>",
    "<ul>\n    <li><b>超低码率语音编码研究</b>：系统研究了在超低码率神经语音编码中引入冻结语义先验（如 HuBERT 和 Whisper）的作用与基本限制。</li>\n    <li><b>揭示“语义收益递减”现象</b>：发现语义约束在极低码率（1.5 kbps）下能显著降低词错误率，但在较高码率（6 kbps 以上）时收益迅速减少。</li>\n    <li><b>动态先验调节策略</b>：提出了一种感知码率的调节策略，动态调整不同先验（偏声学的 HuBERT 和偏语言的 Whisper）的强度，有效平衡了语义一致性和感知自然度，并增强了抗噪性。</li>\n</ul>",
    "<ul>\n    <li><b>跨语言说话人验证难题</b>：针对跨语言场景下语言与说话人特征严重纠缠的问题（即难以正确识别同一个人说不同语言的情况）。</li>\n    <li><b>Dual-LoRA 架构</b>：提出 Dual-LoRA 方法，在冻结的预训练骨干网络中注入可训练的任务分解 LoRA 适配器。</li>\n    <li><b>语言锚定对抗解耦</b>：引入基于明确语言分支的对抗训练，使梯度能精准针对语言线索而非任意相关性，从而在解耦的同时保留关键的说话人特征，在 TidyVoice 基准测试中取得了优异成绩。</li>\n</ul>",
    "<ul>\n    <li><b>情感相似度指标的反思</b>：对语音生成领域中广泛使用的、基于 emotion2vec 等编码器提取的“情感嵌入余弦相似度”指标提出了质疑。</li>\n    <li><b>潜在空间缺陷揭示</b>：通过受控对抗任务和人类对齐测试发现，这些潜在空间由于表征局限性，会受到语言和说话人特征的严重干扰。</li>\n    <li><b>评估指标错位</b>：该指标实际上更倾向于奖励声音的声学模仿，而非真正的情感合成，导致其在零样本相似度评估中无法与人类的真实感知相契合。</li>\n</ul>",
    "<ul>\n    <li><b>口吃预测的突破</b>：训练了一个 61.6 万参数的卷积神经网络，首次在大规模部署级别上实现了从 3 秒音频中预测即将发生的口吃事件，而不仅是检测当前的不流利。</li>\n    <li><b>严重程度选择性与跨人群泛化</b>：发现预测信号主要集中在临床上严重的事件（如阻塞和声音重复）；且模型无需微调即可在不同人群（如儿童）的数据集上实现良好的跨领域泛化。</li>\n    <li><b>完全设备端部署</b>：模型实现了无损导出至 CoreML 等格式，在移动设备（如 iPhone）上具有极低的延迟和极小的算力开销，证明了其实用性和部署潜力。</li>\n</ul>",
    "<ul>\n    <li><b>电影音频目标语音提取</b>：提出了一种知识驱动的方法，用于在存在复杂背景音效的电影音频中提取目标语音。</li>\n    <li><b>发音方式作为先验知识</b>：将从语音帧中检测到的“发音方式”作为知识向量，结合到特征中，以辅助分离那些难以与混合背景声区分的短语音片段。</li>\n    <li><b>分离效果提升</b>：在声音解混叠挑战 (CASS) 数据集上的测试表明，利用这种发音感知知识，特别是对于淹没在背景音中的语音片段，能显著提升语音分离和提取的效果。</li>\n</ul>",
    "<ul>\n    <li><b>多说话人视听语音识别系统</b>：为解决高重叠对话中的目标说话人识别难题，提出了基于长上下文目标说话人视听自动语音识别 (AV-ASR) 模型的 BUT 系统。</li>\n    <li><b>视听特征融合</b>：该架构结合了预训练的 NVIDIA Parakeet-v2 ASR 模型和 AV-HuBERT 模型的视觉表征，能够在单次解码中处理长录音并解决说话人歧义。</li>\n    <li><b>高效聚类与性能领先</b>：采用大语言模型 (Qwen3.5-122B) 估计转录主题相似度以进行对话组聚类，在 CHiME-9 MCoRec 挑战赛中显著优于官方基线，并在评估集中取得第二名。</li>\n</ul>",
    "<ul>\n    <li><b>全新野外视听基准测试</b>：推出了 LRS-VoxMM，这是一个源自 VoxMM 数据集、面向真实复杂场景的视听语音识别 (AVSR) 基准测试。</li>\n    <li><b>场景多样性与格式兼容</b>：该基准测试涵盖了比常用数据集更广泛的场景和声学条件，并预处理为 LRS 风格格式，可直接用于现有的 AVSR 流程。</li>\n    <li><b>验证视觉信息价值</b>：提供了包含噪声、混响等失真的评估集。实验表明，该基准测试更具挑战性，且在声学信号严重退化时，视觉信息对语音识别的贡献尤为明显。</li>\n</ul>",
    "<ul>\n    <li><b>全频谱生物声学分类</b>：旨在打破现有生物声学模型受限于人类听觉频率（预训练在 16 kHz，丢弃了高频信息）的局限，以充分利用动物全频谱（包括超声波）的叫声信息。</li>\n    <li><b>自适应多频带编码框架</b>：研究了一种多频带编码框架，将动物叫声的全频谱分解为多个频带特征，并将它们融合为统一的表征。</li>\n    <li><b>分类性能一致提升</b>：通过相似性分析和分类实验证明，特定的融合策略能产生去相关的频带嵌入，并在多个数据集上一致且显著地优于基带和时间扩展的基线模型。</li>\n</ul>"
]

import os

os.makedirs('data', exist_ok=True)
with open('data/summaries.json', 'w', encoding='utf-8') as f:
    json.dump({"chinese_summaries": chinese_summaries}, f, ensure_ascii=False, indent=2)

print("Created data/summaries.json")
